In [5]:
pip install faker

Collecting faker
  Downloading Faker-19.10.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 8.6 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-19.10.0

In [6]:
from faker import Faker

fake = Faker()

jumlah_data = 10

dummy_data = []

for _ in range(jumlah_data):
    nama = fake.name()
    nomor_telepon = fake.phone_number()
    alamat = fake.address()
    email = fake.email()

    data = f"Nama: {nama}\nNomor Telepon: {nomor_telepon}\nAlamat: {alamat}\nEmail: {email}\n"
    dummy_data.append(data)

file_name = "dummy_data.txt"
with open(file_name, "w") as file:
    for data in dummy_data:
        file.write(data + "\n")

print(f"{jumlah_data} data dummy telah disimpan dalam {file_name}.")

10 data dummy telah disimpan dalam dummy_data.txt.

In [7]:
file_path = "dummy_data.txt"

with open(file_path, "r") as file:

    text = file.read()

print(text)

Nama: Lindsey Lewis
Nomor Telepon: 321-760-8742
Alamat: 8645 Murphy Lane Suite 046
East Jeffrey, RI 54063
Email: yvelasquez@example.com

Nama: Penny Sims
Nomor Telepon: (257)845-7666
Alamat: PSC 2612, Box 9277
APO AA 87624
Email: yjohnson@example.org

Nama: Alicia Moore
Nomor Telepon: +1-456-909-6825x935
Alamat: 7169 Michael Parkways
West Carolyn, MP 55003
Email: marksmith@example.com

Nama: Vanessa Miller
Nomor Telepon: (820)650-3290
Alamat: USS Duncan
FPO AA 22592
Email: christina32@example.net

Nama: Jason Price
Nomor Telepon: 799-547-0331x8560
Alamat: 70259 Mckinney Grove
South John, KS 42484
Email: bettymyers@example.net

Nama: Lisa Neal
Nomor Telepon: 7485153873
Alamat: 0297 Erica Common Suite 044
South Michaelmouth, KY 21425
Email: hector08@example.org

Nama: Jeremy Aguilar
Nomor Telepon: (634)454-2595x890
Alamat: USNV Roberts
FPO AE 29800
Email: ortizmichael@example.com

Nama: Christina Barrett
Nomor Telepon: 329.749.5412x663
Alamat: Unit 6530 Box 0542
DPO AA 58908
Email: hhayes@example.org

Nama: Michael Cruz
Nomor Telepon: 531-721-3583
Alamat: USNV Walters
FPO AE 17290
Email: chad18@example.org

Nama: Jesus Fisher
Nomor Telepon: (952)653-0316x896
Alamat: USNV Carr
FPO AE 56165
Email: omendoza@example.org

In [9]:
import pandas as pd

In [21]:
import re

def extract_info(text):
    # Regex pattern
    name_pattern = r'Nama:\s(.*?)\n'
    phone_pattern = r'Nomor Telepon:\s(.*?)\n'
    address_pattern = r'Alamat:\s(.*?)\n'
    email_pattern = r'Email:\s(.*?)\n'
    email_name_pattern = r'Email:\s(.*?)@'
    #re.findall
    names = re.findall(name_pattern, text)
    phones = re.findall(phone_pattern, text)
    addresses = re.findall(address_pattern, text)
    emails = re.findall(email_pattern, text)
    email_names = re.findall(email_name_pattern, text)
    # Menghilangkan white space,- ,dll serta membuatnya dalam dictionary
    info_list = []
    for i in range(len(names)):
        info_dict = {
            "Name": names[i].strip(),
            "Phone": re.sub(r'\D', '', phones[i]).strip(),
            "Address": addresses[i].strip(),
            "Email": emails[i].strip(),
            "EmailName": email_names[i].strip(),
        }
        info_list.append(info_dict)

    return info_list


info_list = extract_info(text)

for info in info_list:
    print("Name:", info["Name"])
    print("Phone:", info["Phone"])
    print("Address:", info["Address"])
    print("Email:", info["Email"])
    print("Email Name:", info["EmailName"])
    print()

Name: Lindsey Lewis
Phone: 3217608742
Address: 8645 Murphy Lane Suite 046
Email: yvelasquez@example.com
Email Name: yvelasquez

Name: Penny Sims
Phone: 2578457666
Address: PSC 2612, Box 9277
Email: yjohnson@example.org
Email Name: yjohnson

Name: Alicia Moore
Phone: 14569096825935
Address: 7169 Michael Parkways
Email: marksmith@example.com
Email Name: marksmith

Name: Vanessa Miller
Phone: 8206503290
Address: USS Duncan
Email: christina32@example.net
Email Name: christina32

Name: Jason Price
Phone: 79954703318560
Address: 70259 Mckinney Grove
Email: bettymyers@example.net
Email Name: bettymyers

Name: Lisa Neal
Phone: 7485153873
Address: 0297 Erica Common Suite 044
Email: hector08@example.org
Email Name: hector08

Name: Jeremy Aguilar
Phone: 6344542595890
Address: USNV Roberts
Email: ortizmichael@example.com
Email Name: ortizmichael

Name: Christina Barrett
Phone: 3297495412663
Address: Unit 6530 Box 0542
Email: hhayes@example.org
Email Name: hhayes

Name: Michael Cruz
Phone: 5317213583
Address: USNV Walters
Email: chad18@example.org
Email Name: chad18

Name: Jesus Fisher
Phone: 9526530316896
Address: USNV Carr
Email: omendoza@example.org
Email Name: omendoza

In [26]:
df =pd.DataFrame(info_list)

In [27]:
df

,Name,Phone,Address,Email,EmailName
0,Lindsey Lewis,3217608742,8645 Murphy Lane Suite 046,yvelasquez@example.com,yvelasquez
1,Penny Sims,2578457666,"PSC 2612, Box 9277",yjohnson@example.org,yjohnson
2,Alicia Moore,14569096825935,7169 Michael Parkways,marksmith@example.com,marksmith
3,Vanessa Miller,8206503290,USS Duncan,christina32@example.net,christina32
4,Jason Price,79954703318560,70259 Mckinney Grove,bettymyers@example.net,bettymyers
5,Lisa Neal,7485153873,0297 Erica Common Suite 044,hector08@example.org,hector08
6,Jeremy Aguilar,6344542595890,USNV Roberts,ortizmichael@example.com,ortizmichael
7,Christina Barrett,3297495412663,Unit 6530 Box 0542,hhayes@example.org,hhayes
8,Michael Cruz,5317213583,USNV Walters,chad18@example.org,chad18
9,Jesus Fisher,9526530316896,USNV Carr,omendoza@example.org,omendoza

In [30]:
df.to_excel('Prak NLP Regex.xlsx')